imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: @ZeegaExtensionsBundle/Resources/config/services.yml }

framework:
    #esi:             ~
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    translator: { fallback: en }
    session:
        domain: ~
        default_locale: %locale%
        auto_start:     true
        lifetime:       72000
        storage_id:     session.storage.pdo

parameters:
    pdo.db_options:
        db_table:    session
        db_id_col:   session_id
        db_data_col: session_value
        db_time_col: session_time  

services:    
    pdo:
        class: PDO
        arguments:
            - "%database_type%:dbname=%database_name%;host=%database_host%"
            - %database_user%
            - %database_password%
    session.storage.pdo:
            class:     Symfony\Component\HttpFoundation\SessionStorage\PdoSessionStorage
            arguments: [@pdo, %session.storage.options%, %pdo.db_options%]

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        hostname: %hostname%
        directory: %directory%
        web_directory: %web_directory%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  utf8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# fos rest configuration
fos_rest:
    view:
        formats:
            json: true
            rss: false
            xml: false
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig

# fos rest requirement
sensio_framework_extra:
    view:
        annotations: false

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    encryption: %mailer_encryption%    

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: secured_area
    user_class: Zeega\DataBundle\Entity\User
    from_email:
        address: noreply@zeega.org
        sender_name: Zeega
    registration:
        form:
            type: zeega_user_registration
    resetting:
        email:
            template: ZeegaUserBundle:Email:resetting.email.twig

hwi_oauth:
    connect: ~
    resource_owners:
        google:
            type:                google
            client_id:           %google_id%
            client_secret:       %google_secret%
            scope:               https://www.googleapis.com/auth/userinfo.email
            paths:
                email: email
                profilepicture: picture
    fosub:
        username_iterations: 30
        properties:
            google: google_key
    firewall_name: secured_area

nelmio_solarium:
    adapter:
        class: Solarium_Client_Adapter_Http
        host: %solr_host%
        port: %solr_port%
        path: %solr_path%
