security:
    factories:
        - "%kernel.root_dir%/../vendor/bundles/HWI/Bundle/OAuthBundle/Resources/config/security_factory.xml"
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                #csrf_provider: form.csrf_provider
            logout:
                path:   /logout
                target: /login
            anonymous: ~
            oauth:
                resource_owners:
                    google:             "/service/google"
                login_path:        /login/
                failure_path:      /login/oauth

                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge
        search:
            pattern: ^/api/search
            anonymous: ~

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/login/oauth, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[0-9]+, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/register/confirmed, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api/search, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/items, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/projects, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/collections, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/tags, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/routes, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/frames, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/frame, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/layers, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/project, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
