security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                #csrf_provider: form.csrf_provider
            logout:
                path:   /logout
                target: /login
            anonymous: ~
        search:
            pattern: ^/api/search
            anonymous: ~
        oauth:
            oauth_provider:    oauth
            authorization_url: https://github.com/login/oauth/authorize
            access_token_url:  https://github.com/login/oauth/access_token
            infos_url:         https://github.com/api/v2/json/user/show
            username_path:     user.login
            client_id:         <your_oauth_client_id>
            secret:            <your_oauth_secret>
            scope:             <your_oauth_scope>
            check_path:        /secured/login_check
            login_path:        /secured/login
        factories:
                - "%kernel.root_dir%/../vendor/bundles/Knp/Bundle/OAuthBundle/Resources/config/security_factories.xml"    

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/[0-9]+, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/register/confirmed, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api/search, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/items, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/projects, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/collections, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/tags, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/routes, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/frames, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/frame, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/layers, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/project, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
